src/Entity/Sensors.php
<?php

namespace App\Entity;

use App\Repository\SensorsRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Category;
use App\Entity\Room;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SensorsRepository::class)
 */
class Sensors
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(groups = {"put"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\NotBlank(groups = {"post", "delete","put"})
     
     */
    private $Name;

        /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", cascade="remove")
     * @ORM\JoinColumn(name="room_id", referencedColumnName="id")
     * @Assert\NotBlank(groups = {"post", "delete","put"})
     */
    private $Room;

        /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", cascade="remove")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     * @Assert\NotBlank(groups = {"post", "delete","put"})
     */

    private $Category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getRoom()
    {
        return $this->Room;
    }

    public function setRoom(Room $Room): self
    {
        $this->Room = $Room;

        return $this;
    }

    public function getCategory()
    {
        return $this->Category;
    }

    public function setCategory(Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

}

templates/api.twig
<div>
<h1>{{post}}</h1></div>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/menu.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="css/menu.css">
    <title>Smart house</title>
</head>
    <body>
        <div class="title"><h1 style ="margin-left : 15px;">Connect with your smart house !</h1>
        </div>  
        <div class="specs">           
                    <div class = "colspec">
                        {# <div class="form-check">     #}
                            {{form_start(formFilter)}}

                                <div class="from-group" style="margin-left : 15px;">
                                    <label for="">Category : </label>
                                    {{form_widget(formFilter.Category)}} <br>

                                    <label for="">Room : </label>
                                    {{form_widget(formFilter.Room,{'attr': { "style" : "margin-left : 20px; margin-top : 10px;"}})}}<br>

                                    {# {{form_widget(formNewSensor.save, {'attr': {'class' : "btn btn-success"}})}}<br>
                                </div> #}
                                    <button type="submit" class="btn btn-primary" style="margin-top : 10px; margin-bottom : 10px;">Filter</button><br>
                            
                            {{form_end(formFilter)}}
                        {# </div> #}
                    </div>
            <div>
                <div class="newBtn">
                    <form action="/newRoom" class="forms">
                                <button onclick = "/newRoom" class="btn btn-secondary" style="margin-left: 10px; width:90px;">Update Room</button>
                    </form>
                    <form action="/newCategory" class="forms">
                                <button onclick = "/newCategory" class="btn btn-secondary" style="margin-left:10px;">Update Category</button>
                    </form>
                </div>
            </div>
            
            <form action = "/newSensor" >
                <button onclick= "/newSensor" class="btn btn-secondary" style = "margin-left: 10px; width : 250px;margin-top:10px;">Create a new sensor</button>
            </form>

            

        </div>
        <div>
            
        </div>
        
    </div>



    <div class = "cards">
            {% for sensor in sensors %}
                <div class="div1"> 
                    <h3>{{sensor.name}}</h3>
                    <h5>Category : {{sensor.category.name}}</h5>
                    <h5>Room : {{sensor.room.name}}</h5>

                    <div class="button">
                        <button onclick = "Activated('{{sensor.name}}')" type="button" id="{{sensor.name}}" class="btn btn-success Activate" style="margin-right:5px;">Activate {{sensor.name}}</button>
                        <form action = "/update/{{sensor.name}}">
                            <button onclick= "/update/{{sensor.name}}" class="btn btn-warning">Update</button>
                        </form>
                    </div>
                    <div>
                        <form action = "/deleteSensor/{{sensor.id}}" class = "danger">
                            <button onclick= "/deleteSensor/{{sensor.id}}" class="btn btn-danger" style="margin-top:10px;width : 98%;">Delete</button>
                        </form>
                    </div>
                    
                </div>
            {%endfor%}
        </div>

    <script>
        function Activated(id) {
            bouton = document.getElementById(id);

            console.log(bouton.className);

            if("btn btn-success Activate" == bouton.className){
                bouton.classList.remove("btn-success");
                bouton.classList.add("btn-info");
            }else{
                bouton.classList.remove("btn-info");
                bouton.classList.remove("btn");
                bouton.classList.remove("Activate");
                bouton.classList.add("btn");
                bouton.classList.add("btn-success");
                bouton.classList.add("Activate");
            }
            
        }
    </script>

    </body>
</html>

templates/newCategory.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="css/menu.css">
    <title>Update information</title>
</head>
<body>
    <div class="title"><h1 style ="margin-left : 15px;">Connect with your smart house !</h1>
    </div> 
        <div class = "bloc" > 
            <div class = "formNew" style = "width : 330px;">

                <div>
                    <h3>Create a new category !</h3>
                    
                    {{form_start(formCategory)}}

                        <div class="from-group">
                            <label for="">Name of the category : </label>
                            {{form_widget(formCategory.Name)}}<br>

                            {{form_widget(formCategory.save, {'attr': {'class' : "btn btn-success", "style" : "margin-top : 10px;"}})}}<br>
                        </div>
                    
                    {{form_end(formCategory)}}

                
                    <form action = "/" style = "float : right;">
                        <button onclick= "/" class="btn btn-warning">Back to menu</button>
                    </form>
                </div>
            </div>

            <div class = "formNew" style = "width : 330px;">
                <div style = "height : 200px;">
                    <h3>Delete a category !</h3>
                    
                    {{form_start(formDelete)}}

                        <div class="from-group">
                            <label for="">Name of the room : </label>
                            {{form_widget(formDelete.Category)}}<br>

                            {{form_widget(formDelete.save, {'attr': {'class' : "btn btn-danger", "style" : "margin-top : 10px;"}})}}<br>
                        </div>
                    
                    {{form_end(formDelete)}}

                
                    <form action = "/" style = "float : right;">
                        <button onclick= "/" class="btn btn-warning">Back to menu</button>
                    </form>
                </div>
            </div>
        </div>

</body>
</html>

templates/newRoom.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="css/menu.css">
    <title>Update information</title>
</head>

<body>
    <div class="title"><h1 style ="margin-left : 15px;">Connect with your smart house !</h1></div>
    <div class="bloc">
        <div class = "formNew">
            {{form_start(formRoom)}}
            <h3>Create a new room !</h3>
            <div class="from-group">
                <label for="">Name of the room : </label>
                {{form_widget(formRoom.Name)}}<br>
                {{form_widget(formRoom.save, {'attr': {'class' : "btn btn-success", "style" : "margin-top : 10px;"}})}}<br>
            </div>
            {{form_end(formRoom)}}
            <form action = "/" style = "float : right;">
                <button onclick= "/" class="btn btn-warning">Back to menu</button>
            </form>
        </div>
        <div class = "formNew">
            {{form_start(formDelete)}}
            <h3>Delete a room !</h3>
            <div class="from-group">
                <label for="">Name of the room : </label>
                {{form_widget(formDelete.Room)}}<br>
                {{form_widget(formDelete.save, {'attr': {'class' : "btn btn-danger", "style" : "margin-top : 10px;"}})}}<br>
            </div>  
            {{form_end(formDelete)}}
            <form action = "/" style = "float : right;">
                <button onclick= "/" class="btn btn-warning">Back to menu</button>
            </form>
        </div>
    </div>
</body>
</html>

templates/newSensor.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="css/menu.css">
    <title>Update information</title>
</head>
<body>
    <div class="title"><h1 style ="margin-left : 15px;">Connect with your smart house !</h1>
    </div> 
    <div class="formNew" style = "width : 400px; height : 250px;"> 
        <div style = "margin-left : 15px;">
            <h3>Add your new sensor here ! </h3>
            
            {{form_start(formNewSensor)}}

                <div class="from-group">
                    <label for="">Name : </label>
                    {{form_widget(formNewSensor.Name,{'attr': { "style" : "margin-left : 20px; margin-bottom : 10px;"}})}} <br>

                    <label for="">Category : </label>
                    {{form_widget(formNewSensor.Category,{'attr': { "style" : "margin-bottom : 10px;"}})}} <br>

                    <label for="">Room : </label>
                    {{form_widget(formNewSensor.Room,{'attr': { "style" : "margin-left : 20px;"}})}}<br>

                    {# {{form_widget(formNewSensor.save, {'attr': {'class' : "btn btn-success"}})}}<br>
                </div> #}
                    <button type="submit" class ="btn btn-success" style = "margin-top : 10px;">Create</button><br>
            
            {{form_end(formNewSensor)}}

            <form action = "/" style = "float : right;">
                <button onclick= "/" class="btn btn-warning">Back to menu</button>
            </form>
        </div>
    </div>

  

</body>
</html>

templates/update.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/menu.css">
    <title>Update information</title>
</head>
<body>
    <div class="title"><h1 style ="margin-left : 15px;">Connect with your smart house !</h1>
    </div>
    <div class="formNew" style = "height : 210px;"> 
        <div> 
            <h3>{{sensor.name}}</h3>
            
            {{form_start(formUpdate)}}

                <div class="from-group">
                    <label for="">Category : </label>
                    {{form_widget(formUpdate.Category,{'attr': { "style" : "margin-bottom : 10px;"}})}} <br>

                    <label for="">Room : </label>
                    {{form_widget(formUpdate.Room,{'attr': { "style" : "margin-left : 20px;"}})}}<br>

                    {{form_widget(formUpdate.save, {'attr': {'class' : "btn btn-success", "style" : "margin-top : 10px;"}})}}<br>
                </div>
            
            {{form_end(formUpdate)}}
        </div>
        <div>
            <form action = "/" style = "float : right;">
                <button onclick= "/" class="btn btn-warning">Back to menu</button>
            </form>
        </div>
    </div>

</body>
</html>